name: venv
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - python=3.11.4
  - scanpy=1.9.3
  - pandas=2.0.3
  - seaborn=0.12.2
  - python-igraph
  - leidenalg=0.9.1
  - matplotlib=3.7.1
  - jupyter=1.0.0
  - jupyterlab=4.0.2
  - notebook=6.5.4
  - jupyterlab
  - rpy2=3.5.11
  - muon
  - openpyxl
  - celltypist=0.1.9
  - pydeseq2=0.4.0
  - termcolor
  - adjustText
  - anndata2ri
  - scirpy=0.13.1
  - numpy=1.26.1

  - pip
    - bioinfokit=2.1.3
  
# prefix: /opt/homebrew/Caskroom/miniconda/base/envs/venv
